# Project information
site_name: VIA University College
site_url: https://rbrooksdk.github.io/math_kickstarter
site_author: Richard Brooks
site_description: Self-paced mathematics brush-up for engineering students at VIA University College
docs_dir: .
site_dir: site
exclude_docs: |
  site/
  scripts/
  .venv/
  .github/
  requirements.txt
# Repository information
repo_name: Github
repo_url: https://github.com/RBrooksDK/math_kickstarter

# Copyright
copyright: Copyright &copy; 2026 Richard Brooks

# Configurations
theme:
  name: material
  language: en
  default_theme: default
  # custom_dir: overrides
  favicon: figures/vialogo_white.png
  logo: figures/vialogo.png
  icon:
    repo: fontawesome/brands/github
    annotation: material/chevron-right-circle
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    # - navigation.indexes
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: orange
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: "VIA Type"
    code: "Roboto Mono"

plugins:
  - same-dir
  - search
  - mkdocs_quiz:
      lang: en

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/js/all.min.js

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: material/email
      link: mailto:rib@via.dk
    - icon: fontawesome/brands/github
      link: https://github.com/RBrooksDK/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rbrooks-dk/

extra_css:
  - stylesheets/extra.css

nav:
  - Home: README.md
  - Topics:
    - Topics/README.md
    - Basic Arithmetic and Equations: basic_arithmetic_and_equations/README.md
    - Functions: functions/README.md
    - Differential Calculus: differential_calculus/README.md
    - Integral Calculus: integral_calculus/README.md
    - Vectors in 2D: vectors/README.md
  - FAQ: pages/faq.md